export const Evaluations = [
  {
    name: "Evelyn",
    assignment: "SCRUM",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W1D1-1",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Evelyn",
    assignment: "W1D2-1",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Evelyn",
    assignment: "W1D2-2",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W1D2-3",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Evelyn",
    assignment: "W1D2-4",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W1D2-5",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W1D3-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W1D3-2",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W1D3-4",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W1D3-5",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 5,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W1D4-1",
    difficulty: 4,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W1D5 - Project - Galgje",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Evelyn",
    assignment: "W2D1-1",
    difficulty: 1,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W2D1-2",
    difficulty: 2,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W2D2-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W2D2-2",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W2D2-3",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W2D3-1",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W2D3-2",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Evelyn",
    assignment: "W2D3-3",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W2D4-1",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Evelyn",
    assignment: "W2D4-2",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W2D4-3",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Evelyn",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W3D1-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W3D1-2",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W3D1-3",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W3D1-4",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Evelyn",
    assignment: "W3D2-1",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W3D2-2",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Evelyn",
    assignment: "W3D2-3",
    difficulty: 3,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W3D3-1",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W3D3-2",
    difficulty: 4,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W3D3-3",
    difficulty: 3,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W3D3-4",
    difficulty: 4,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W3D4-1",
    difficulty: 5,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W3D4-2",
    difficulty: 1,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 2,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W4D2-1",
    difficulty: 1,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W4D2-2",
    difficulty: 1,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W4D2-3",
    difficulty: 1,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W4D2-4",
    difficulty: 1,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W4D3-1",
    difficulty: 1,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W4D3-2",
    difficulty: 1,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W4D3-3",
    difficulty: 1,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W4D3-4",
    difficulty: 1,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W4D3-5",
    difficulty: 1,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 1,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W5D4-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Evelyn",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Evelyn",
    assignment: "W6D1-1",
    difficulty: 5,
    fun: 5,
  },
  {
    name: "Evelyn",
    assignment: "W6D2-1",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Evelyn",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 5,
    fun: 5,
  },
  {
    name: "Aranka",
    assignment: "SCRUM",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Aranka",
    assignment: "W1D1-1",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W1D2-1",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Aranka",
    assignment: "W1D2-2",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Aranka",
    assignment: "W1D2-3",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Aranka",
    assignment: "W1D2-4",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W1D2-5",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Aranka",
    assignment: "W1D3-1",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Aranka",
    assignment: "W1D3-2",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Aranka",
    assignment: "W1D3-4",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Aranka",
    assignment: "W1D3-5",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Aranka",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W1D4-1",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Aranka",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W1D5 - Project - Galgje",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Aranka",
    assignment: "W2D1-1",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Aranka",
    assignment: "W2D1-2",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Aranka",
    assignment: "W2D2-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Aranka",
    assignment: "W2D2-2",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Aranka",
    assignment: "W2D2-3",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Aranka",
    assignment: "W2D3-1",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W2D3-2",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Aranka",
    assignment: "W2D3-3",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Aranka",
    assignment: "W2D4-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Aranka",
    assignment: "W2D4-2",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W2D4-3",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Aranka",
    assignment: "W3D1-1",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Aranka",
    assignment: "W3D1-2",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Aranka",
    assignment: "W3D1-3",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Aranka",
    assignment: "W3D1-4",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W3D2-1",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W3D2-2",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W3D2-3",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W3D3-1",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Aranka",
    assignment: "W3D3-2",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W3D3-3",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W3D3-4",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W3D4-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Aranka",
    assignment: "W3D4-2",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Aranka",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Aranka",
    assignment: "W4D2-1",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Aranka",
    assignment: "W4D2-2",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Aranka",
    assignment: "W4D2-3",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Aranka",
    assignment: "W4D2-4",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Aranka",
    assignment: "W4D3-1",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Aranka",
    assignment: "W4D3-2",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Aranka",
    assignment: "W4D3-3",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Aranka",
    assignment: "W4D3-4",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Aranka",
    assignment: "W4D3-5",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Aranka",
    assignment: "W5D4-1",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Aranka",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Aranka",
    assignment: "W6D1-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Aranka",
    assignment: "W6D2-1",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Aranka",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Floris",
    assignment: "SCRUM",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Floris",
    assignment: "W1D1-1",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Floris",
    assignment: "W1D2-1",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W1D2-2",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Floris",
    assignment: "W1D2-3",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Floris",
    assignment: "W1D2-4",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Floris",
    assignment: "W1D2-5",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Floris",
    assignment: "W1D3-1",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Floris",
    assignment: "W1D3-2",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Floris",
    assignment: "W1D3-4",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W1D3-5",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Floris",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W1D4-1",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Floris",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Floris",
    assignment: "W1D5 - Project - Galgje",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Floris",
    assignment: "W2D1-1",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W2D1-2",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Floris",
    assignment: "W2D2-1",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Floris",
    assignment: "W2D2-2",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W2D2-3",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W2D3-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Floris",
    assignment: "W2D3-2",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W2D3-3",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Floris",
    assignment: "W2D4-1",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Floris",
    assignment: "W2D4-2",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Floris",
    assignment: "W2D4-3",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Floris",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Floris",
    assignment: "W3D1-1",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Floris",
    assignment: "W3D1-2",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Floris",
    assignment: "W3D1-3",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Floris",
    assignment: "W3D1-4",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Floris",
    assignment: "W3D2-1",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W3D2-2",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W3D2-3",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W3D3-1",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Floris",
    assignment: "W3D3-2",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Floris",
    assignment: "W3D3-3",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Floris",
    assignment: "W3D3-4",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W3D4-1",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Floris",
    assignment: "W3D4-2",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W4D2-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Floris",
    assignment: "W4D2-2",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Floris",
    assignment: "W4D2-3",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Floris",
    assignment: "W4D2-4",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W4D3-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Floris",
    assignment: "W4D3-2",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Floris",
    assignment: "W4D3-3",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W4D3-4",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W4D3-5",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Floris",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W5D4-1",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Floris",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Floris",
    assignment: "W6D1-1",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Floris",
    assignment: "W6D2-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Floris",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "SCRUM",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Hector",
    assignment: "W1D1-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Hector",
    assignment: "W1D2-1",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Hector",
    assignment: "W1D2-2",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Hector",
    assignment: "W1D2-3",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Hector",
    assignment: "W1D2-4",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Hector",
    assignment: "W1D2-5",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W1D3-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Hector",
    assignment: "W1D3-2",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Hector",
    assignment: "W1D3-4",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W1D3-5",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Hector",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W1D4-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Hector",
    assignment: "W1D5 - Project - Galgje",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Hector",
    assignment: "W2D1-1",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Hector",
    assignment: "W2D1-2",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Hector",
    assignment: "W2D2-1",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Hector",
    assignment: "W2D2-2",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Hector",
    assignment: "W2D2-3",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Hector",
    assignment: "W2D3-1",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W2D3-2",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Hector",
    assignment: "W2D3-3",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Hector",
    assignment: "W2D4-1",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Hector",
    assignment: "W2D4-2",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W2D4-3",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Hector",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W3D1-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W3D1-2",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Hector",
    assignment: "W3D1-3",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Hector",
    assignment: "W3D1-4",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Hector",
    assignment: "W3D2-1",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Hector",
    assignment: "W3D2-2",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Hector",
    assignment: "W3D2-3",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W3D3-1",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Hector",
    assignment: "W3D3-2",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W3D3-3",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Hector",
    assignment: "W3D3-4",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W3D4-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Hector",
    assignment: "W3D4-2",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Hector",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Hector",
    assignment: "W4D2-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W4D2-2",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W4D2-3",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Hector",
    assignment: "W4D2-4",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Hector",
    assignment: "W4D3-1",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Hector",
    assignment: "W4D3-2",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Hector",
    assignment: "W4D3-3",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W4D3-4",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Hector",
    assignment: "W4D3-5",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Hector",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W5D4-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Hector",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W6D1-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Hector",
    assignment: "W6D2-1",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Hector",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "SCRUM",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W1D1-1",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W1D2-1",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Martina",
    assignment: "W1D2-2",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W1D2-3",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W1D2-4",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Martina",
    assignment: "W1D2-5",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W1D3-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W1D3-2",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W1D3-4",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Martina",
    assignment: "W1D3-5",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Martina",
    assignment: "W1D4-1",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Martina",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Martina",
    assignment: "W1D5 - Project - Galgje",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W2D1-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W2D1-2",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Martina",
    assignment: "W2D2-1",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W2D2-2",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Martina",
    assignment: "W2D2-3",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W2D3-1",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Martina",
    assignment: "W2D3-2",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W2D3-3",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Martina",
    assignment: "W2D4-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W2D4-2",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W2D4-3",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W3D1-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W3D1-2",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Martina",
    assignment: "W3D1-3",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W3D1-4",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Martina",
    assignment: "W3D2-1",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Martina",
    assignment: "W3D2-2",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W3D2-3",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W3D3-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W3D3-2",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W3D3-3",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Martina",
    assignment: "W3D3-4",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Martina",
    assignment: "W3D4-1",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W3D4-2",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Martina",
    assignment: "W4D2-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W4D2-2",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Martina",
    assignment: "W4D2-3",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W4D2-4",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W4D3-1",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W4D3-2",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Martina",
    assignment: "W4D3-3",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W4D3-4",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W4D3-5",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Martina",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W5D4-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W6D1-1",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Martina",
    assignment: "W6D2-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Martina",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Maurits",
    assignment: "SCRUM",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Maurits",
    assignment: "W1D1-1",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W1D2-1",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Maurits",
    assignment: "W1D2-2",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Maurits",
    assignment: "W1D2-3",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Maurits",
    assignment: "W1D2-4",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Maurits",
    assignment: "W1D2-5",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W1D3-1",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Maurits",
    assignment: "W1D3-2",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Maurits",
    assignment: "W1D3-4",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Maurits",
    assignment: "W1D3-5",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Maurits",
    assignment: "W1D4-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Maurits",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Maurits",
    assignment: "W1D5 - Project - Galgje",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Maurits",
    assignment: "W2D1-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Maurits",
    assignment: "W2D1-2",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W2D2-1",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Maurits",
    assignment: "W2D2-2",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Maurits",
    assignment: "W2D2-3",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Maurits",
    assignment: "W2D3-1",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Maurits",
    assignment: "W2D3-2",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W2D3-3",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Maurits",
    assignment: "W2D4-1",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W2D4-2",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Maurits",
    assignment: "W2D4-3",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Maurits",
    assignment: "W3D1-1",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Maurits",
    assignment: "W3D1-2",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W3D1-3",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Maurits",
    assignment: "W3D1-4",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Maurits",
    assignment: "W3D2-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Maurits",
    assignment: "W3D2-2",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Maurits",
    assignment: "W3D2-3",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W3D3-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Maurits",
    assignment: "W3D3-2",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Maurits",
    assignment: "W3D3-3",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W3D3-4",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Maurits",
    assignment: "W3D4-1",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Maurits",
    assignment: "W3D4-2",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Maurits",
    assignment: "W4D2-1",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Maurits",
    assignment: "W4D2-2",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Maurits",
    assignment: "W4D2-3",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Maurits",
    assignment: "W4D2-4",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W4D3-1",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Maurits",
    assignment: "W4D3-2",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Maurits",
    assignment: "W4D3-3",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Maurits",
    assignment: "W4D3-4",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W4D3-5",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Maurits",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W5D4-1",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Maurits",
    assignment: "W6D1-1",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Maurits",
    assignment: "W6D2-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Maurits",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Rahima",
    assignment: "SCRUM",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W1D1-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W1D2-1",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W1D2-2",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Rahima",
    assignment: "W1D2-3",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Rahima",
    assignment: "W1D2-4",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Rahima",
    assignment: "W1D2-5",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Rahima",
    assignment: "W1D3-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Rahima",
    assignment: "W1D3-2",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W1D3-4",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Rahima",
    assignment: "W1D3-5",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Rahima",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Rahima",
    assignment: "W1D4-1",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Rahima",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W1D5 - Project - Galgje",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Rahima",
    assignment: "W2D1-1",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Rahima",
    assignment: "W2D1-2",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Rahima",
    assignment: "W2D2-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Rahima",
    assignment: "W2D2-2",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Rahima",
    assignment: "W2D2-3",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Rahima",
    assignment: "W2D3-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Rahima",
    assignment: "W2D3-2",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W2D3-3",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Rahima",
    assignment: "W2D4-1",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W2D4-2",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W2D4-3",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Rahima",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Rahima",
    assignment: "W3D1-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Rahima",
    assignment: "W3D1-2",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Rahima",
    assignment: "W3D1-3",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Rahima",
    assignment: "W3D1-4",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W3D2-1",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Rahima",
    assignment: "W3D2-2",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W3D2-3",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Rahima",
    assignment: "W3D3-1",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Rahima",
    assignment: "W3D3-2",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W3D3-3",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W3D3-4",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Rahima",
    assignment: "W3D4-1",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Rahima",
    assignment: "W3D4-2",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Rahima",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W4D2-1",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W4D2-2",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Rahima",
    assignment: "W4D2-3",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Rahima",
    assignment: "W4D2-4",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Rahima",
    assignment: "W4D3-1",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Rahima",
    assignment: "W4D3-2",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Rahima",
    assignment: "W4D3-3",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Rahima",
    assignment: "W4D3-4",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Rahima",
    assignment: "W4D3-5",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Rahima",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Rahima",
    assignment: "W5D4-1",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Rahima",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Rahima",
    assignment: "W6D1-1",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W6D2-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Rahima",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Sandra",
    assignment: "SCRUM",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Sandra",
    assignment: "W1D1-1",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W1D2-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W1D2-2",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Sandra",
    assignment: "W1D2-3",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W1D2-4",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Sandra",
    assignment: "W1D2-5",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W1D3-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Sandra",
    assignment: "W1D3-2",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Sandra",
    assignment: "W1D3-4",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W1D3-5",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W1D4-1",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Sandra",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W1D5 - Project - Galgje",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W2D1-1",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Sandra",
    assignment: "W2D1-2",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W2D2-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W2D2-2",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W2D2-3",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W2D3-1",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Sandra",
    assignment: "W2D3-2",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Sandra",
    assignment: "W2D3-3",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Sandra",
    assignment: "W2D4-1",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W2D4-2",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W2D4-3",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Sandra",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W3D1-1",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W3D1-2",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W3D1-3",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W3D1-4",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Sandra",
    assignment: "W3D2-1",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W3D2-2",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W3D2-3",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Sandra",
    assignment: "W3D3-1",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Sandra",
    assignment: "W3D3-2",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Sandra",
    assignment: "W3D3-3",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W3D3-4",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Sandra",
    assignment: "W3D4-1",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W3D4-2",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Sandra",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Sandra",
    assignment: "W4D2-1",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W4D2-2",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Sandra",
    assignment: "W4D2-3",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W4D2-4",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W4D3-1",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Sandra",
    assignment: "W4D3-2",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W4D3-3",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W4D3-4",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W4D3-5",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W5D4-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Sandra",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Sandra",
    assignment: "W6D1-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Sandra",
    assignment: "W6D2-1",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Sandra",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Wietske",
    assignment: "SCRUM",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Wietske",
    assignment: "W1D1-1",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Wietske",
    assignment: "W1D2-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W1D2-2",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Wietske",
    assignment: "W1D2-3",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Wietske",
    assignment: "W1D2-4",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Wietske",
    assignment: "W1D2-5",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W1D3-1",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Wietske",
    assignment: "W1D3-2",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W1D3-4",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Wietske",
    assignment: "W1D3-5",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W1D4-1",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Wietske",
    assignment: "W1D5 - Project - Galgje",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Wietske",
    assignment: "W2D1-1",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Wietske",
    assignment: "W2D1-2",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Wietske",
    assignment: "W2D2-1",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Wietske",
    assignment: "W2D2-2",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W2D2-3",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W2D3-1",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Wietske",
    assignment: "W2D3-2",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Wietske",
    assignment: "W2D3-3",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Wietske",
    assignment: "W2D4-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Wietske",
    assignment: "W2D4-2",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W2D4-3",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Wietske",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Wietske",
    assignment: "W3D1-1",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Wietske",
    assignment: "W3D1-2",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W3D1-3",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Wietske",
    assignment: "W3D1-4",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W3D2-1",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Wietske",
    assignment: "W3D2-2",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Wietske",
    assignment: "W3D2-3",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W3D3-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W3D3-2",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Wietske",
    assignment: "W3D3-3",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Wietske",
    assignment: "W3D3-4",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W3D4-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W3D4-2",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Wietske",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W4D2-1",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Wietske",
    assignment: "W4D2-2",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W4D2-3",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Wietske",
    assignment: "W4D2-4",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Wietske",
    assignment: "W4D3-1",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Wietske",
    assignment: "W4D3-2",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Wietske",
    assignment: "W4D3-3",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W4D3-4",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Wietske",
    assignment: "W4D3-5",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Wietske",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Wietske",
    assignment: "W5D4-1",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Wietske",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Wietske",
    assignment: "W6D1-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Wietske",
    assignment: "W6D2-1",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Wietske",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Storm",
    assignment: "SCRUM",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Storm",
    assignment: "W1D1-1",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Storm",
    assignment: "W1D2-1",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Storm",
    assignment: "W1D2-2",
    difficulty: 1,
    fun: 3,
  },
  {
    name: "Storm",
    assignment: "W1D2-3",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Storm",
    assignment: "W1D2-4",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Storm",
    assignment: "W1D2-5",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Storm",
    assignment: "W1D3-1",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Storm",
    assignment: "W1D3-2",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Storm",
    assignment: "W1D3-4",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Storm",
    assignment: "W1D3-5",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Storm",
    assignment: "W1D3 - Project - Guess-the-number",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Storm",
    assignment: "W1D4-1",
    difficulty: 4,
    fun: 2,
  },
  {
    name: "Storm",
    assignment: "W1D4 - Project - Kleurentoggle",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Storm",
    assignment: "W1D5 - Project - Galgje",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Storm",
    assignment: "W2D1-1",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Storm",
    assignment: "W2D1-2",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Storm",
    assignment: "W2D2-1",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Storm",
    assignment: "W2D2-2",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Storm",
    assignment: "W2D2-3",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Storm",
    assignment: "W2D3-1",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Storm",
    assignment: "W2D3-2",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Storm",
    assignment: "W2D3-3",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Storm",
    assignment: "W2D4-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Storm",
    assignment: "W2D4-2",
    difficulty: 4,
    fun: 3,
  },
  {
    name: "Storm",
    assignment: "W2D4-3",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Storm",
    assignment: "W2D5 - Project - Filmzoeker",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Storm",
    assignment: "W3D1-1",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Storm",
    assignment: "W3D1-2",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Storm",
    assignment: "W3D1-3",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Storm",
    assignment: "W3D1-4",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Storm",
    assignment: "W3D2-1",
    difficulty: 1,
    fun: 4,
  },
  {
    name: "Storm",
    assignment: "W3D2-2",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Storm",
    assignment: "W3D2-3",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Storm",
    assignment: "W3D3-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Storm",
    assignment: "W3D3-2",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Storm",
    assignment: "W3D3-3",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Storm",
    assignment: "W3D3-4",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Storm",
    assignment: "W3D4-1",
    difficulty: 2,
    fun: 4,
  },
  {
    name: "Storm",
    assignment: "W3D4-2",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Storm",
    assignment: "W3D5 - Project - Todo-List",
    difficulty: 3,
    fun: 2,
  },
  {
    name: "Storm",
    assignment: "W4D2-1",
    difficulty: 2,
    fun: 1,
  },
  {
    name: "Storm",
    assignment: "W4D2-2",
    difficulty: 3,
    fun: 3,
  },
  {
    name: "Storm",
    assignment: "W4D2-3",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Storm",
    assignment: "W4D2-4",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Storm",
    assignment: "W4D3-1",
    difficulty: 3,
    fun: 4,
  },
  {
    name: "Storm",
    assignment: "W4D3-2",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Storm",
    assignment: "W4D3-3",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Storm",
    assignment: "W4D3-4",
    difficulty: 3,
    fun: 1,
  },
  {
    name: "Storm",
    assignment: "W4D3-5",
    difficulty: 2,
    fun: 3,
  },
  {
    name: "Storm",
    assignment: "W4D3 - Project - Next-Level CSS",
    difficulty: 4,
    fun: 1,
  },
  {
    name: "Storm",
    assignment: "W5D4-1",
    difficulty: 2,
    fun: 2,
  },
  {
    name: "Storm",
    assignment: "W5D5 - Project - Lil_Playlist",
    difficulty: 1,
    fun: 2,
  },
  {
    name: "Storm",
    assignment: "W6D1-1",
    difficulty: 4,
    fun: 4,
  },
  {
    name: "Storm",
    assignment: "W6D2-1",
    difficulty: 1,
    fun: 1,
  },
  {
    name: "Storm",
    assignment: "W6D2 - Project - Eindopdracht",
    difficulty: 3,
    fun: 3,
  },
];

const students = [
  {
    id: 1,
    lastName: "Winterbottom",
    phone: "714-457-0817",
    email: "awinterbottom0@abc.net.au",
    avatar: "https://robohash.org/quiestaut.jpg?size=200x200&set=set1",
  },
  {
    id: 2,
    lastName: "Garlicke",
    phone: "569-485-6075",
    email: "kgarlicke1@blog.com",
    avatar:
      "https://robohash.org/reprehenderitdoloret.jpg?size=200x200&set=set1",
  },
  {
    id: 3,
    lastName: "Grgic",
    phone: "831-444-9100",
    email: "ogrgic2@google.es",
    avatar: "https://robohash.org/nesciuntaddolores.jpg?size=200x200&set=set1",
  },
  {
    id: 4,
    lastName: "Kneath",
    phone: "847-483-7090",
    email: "tkneath3@smugmug.com",
    avatar: "https://robohash.org/dictaidiusto.jpg?size=200x200&set=set1",
  },
  {
    id: 5,
    lastName: "Filipchikov",
    phone: "635-734-9074",
    email: "efilipchikov4@a8.net",
    avatar:
      "https://robohash.org/etreprehenderitnisi.jpg?size=200x200&set=set1",
  },
  {
    id: 6,
    lastName: "Aries",
    phone: "452-895-0914",
    email: "daries5@chicagotribune.com",
    avatar: "https://robohash.org/eligendirationenon.jpg?size=200x200&set=set1",
  },
  {
    id: 7,
    lastName: "Toe",
    phone: "378-950-8681",
    email: "btoe6@parallels.com",
    avatar:
      "https://robohash.org/assumendasapienteoptio.jpg?size=200x200&set=set1",
  },
  {
    id: 8,
    lastName: "Yashunin",
    phone: "377-405-8019",
    email: "kyashunin7@sina.com.cn",
    avatar:
      "https://robohash.org/laborumdoloremaliquam.jpg?size=200x200&set=set1",
  },
  {
    id: 9,
    lastName: "Trounce",
    phone: "734-634-3372",
    email: "ytrounce8@wisc.edu",
    avatar:
      "https://robohash.org/blanditiiscupiditatedignissimos.jpg?size=200x200&set=set1",
  },
  {
    id: 10,
    lastName: "Janikowski",
    phone: "261-535-5724",
    email: "ljanikowski9@java.com",
    avatar: "https://robohash.org/ducimusetomnis.jpg?size=200x200&set=set1",
  },
];

const studentNames = [];
Evaluations.forEach((evaluation) => {
  if (!studentNames.includes(evaluation.name))
    studentNames.push(evaluation.name);
});

export const Students = students.map((student, index) => {
  return {
    ...student,
    firstName: studentNames[index],
  };
});
